- index.js
- test/fixtures/places-z0-0-0.json
- test/fixtures/places.json
- test/test.js
Fixes getTile to wrap clusters within a buffer distance from the dateline so that they’re included on both sides. cc @jfirebaugh
> Fix tile clusters around dateline

- demo/worker.js
In Firefox, you get a weird error aka *"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"* in the console and the cluster is not shown.
According to https://davidwalsh.name/fix-javascript-errors, it seems it's due to the fact that line `xhr.responseType = 'json';` should be set after an `xhr.open`.
Changing the following in demo/worker.js
xhr.responseType = 'json';
xhr.open('GET', url, true);:
with
xhr.open('GET', url, true);
xhr.responseType = 'json';
make things work in both Firefox and Chrome.
This PR is the above fix for this case.
> Fix error related to anticipated call to set xhr.responseType in Firefox

- index.js
- test/fixtures/places-z0-0-0.json
Fixes #13. This is a fast approach replacing changes proposed in #27 and #30. Also addresses https://github.com/mapbox/mapbox-gl-js/issues/3318.
It pretty much doesn't affect performance while allowing to accurately fetch "children" clusters, either for spiderfying, generating a hull, precise "zoom to cluster" or any other features.
The way it works is storing the index of the "origin" point the cluster was created from as its id, and also storing `parentId` for each point/cluster that was clustered. Then you can fetch the "origin" point, do a radius query around it on the next zoom and filter out points that are not related to the cluster. This operation is almost instant since it's `O(log N)`.
Let me know what you think!
cc @apkoponen @bewithjonam @stepankuzmin
> getChildren method for getting children of a cluster on the next zoom

- index.js
- test/test.js
Building on #31, this PR adds a method for a super-fast retrieval of leaf points in a cluster with pagination support. This is the second part of solving https://github.com/mapbox/mapbox-gl-js/issues/3318, allowing us to create a UI where you can click on a cluster and get a paginated view of all points in it with ability to jump between pages.
Usage is as follows:
```js
index.getLeaves(
clusterId, // cluster_id property of the clicked cluster
zoom,      // zoom of the clicked cluster
limit,     // how many points to return; 10 by default
offset);   // how many points to skip for pagination; 0 by default
```
Since this is basically depth-first spatial tree traversal, the call is very fast — e.g. getting 1000 points starting from the 200,000-th from a 400,000-point cluster takes just …
> add getLeaves method for retrieving leaf points (paginated)

- index.js
- test/test.js
Closes #6. Given a clusterId (with its zoom), returns the zoom on which this cluster expands into multiple clusters or points. This probably covers what most people need when they ask for "click on cluster to zoom to it", and provides a better experience than "zoom to cluster's bounding box".
cc @hyperknot @itamair
> Add getClusterExpansionZoom method

- index.js
- package.json
- test/test.js
I thought a lot about API design for cluster property aggregations because once we commit to a particular API, it will be difficult to change, and doing support/maintenance for such a complex feature may be a big burden.
In this PR, I'm proposing an alternative implementation to #12 and @redbmk's [fork](https://github.com/redbmk/supercluster), inspired by the [map-reduce concept](https://en.wikipedia.org/wiki/MapReduce). It should hopefully eliminate all the API ambiguity and make writing custom aggregations easier.
- the `initial` function returns the initial properties of a cluster (before accumulation)
- the `map` function specifies how to interpret individual points (as opposed to clusters) when accumulating properties
- the `reduce` function does the accumulation and is similar to …
> Implement map/reduce for custom cluster properties

- index.js
I repeated the code that share same logic, maybe better for readability.
> refactor code

- index.js
- test/fixtures/places.json
It is valid for GeoJSON features to have a null geometry, this PR aims to ignores such features rather than crashing.
> ignore features with null geometry

- index.js
- test/fixtures/places-z0-0-0.json
- test/test.js
This PR merges `clusterZoom` into `clusterId` so there's just one number to keep track of, simplifying API for `getLeaves`, `getChildren` and `getClusterExpansionZoom` methods, and introducing a descriptive error in case `clusterId` is invalid. 
Closes #43. Since cluster ids will change, this PR is breaking, probably warranting a major release.
cc @almirfilho @myflowpl
> Simplify clusterId-related API methods

- index.js
Mainly used for Typescript support, other bundlers like Rollup/Babel use some other "magic" to support default exports.
Same thing was done for [concaveman](https://github.com/mapbox/concaveman/blob/master/index.js#L9-L10) & polylabel (PR https://github.com/mapbox/polylabel/pull/10):
An update to the Typescript definition has already been made to reflect this change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20348
```js
import supercluster from 'supercluster'
```
Gets compile to:
```js
'use strict';
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
var supercluster = _interopDefault(require('supercluster'));
```
```js
import * as supercluster from 'supercluster'
```
Gets compile to:
```js
'use strict'; …
```
> Support export default (Typescript related)

- bench.js
- demo/worker.js
- index.js
- rollup.config.js
- test/test.js
Switches from `supercluster(...)` factory to `new Supercluster(...)` class instantiation, which is more flexible and idiomatic in modern ES, although a breaking change. Will be released in v5.
Closes #99.
> Switch to class-based API (idiomatic ES)

- README.md
- index.js
- test/test.js
This makes `map`/`reduce` more convenient to use by making it possible to omit the `initial` function in most cases.
When `initial` is omitted, the reducer will use the mapped values of the first reduced item as the initial value. So trivial cases like `+`, `min` and `max` will work seamlessly without the need for `initial`.
It's kind of breaking, but I doubt many people depended on `initial` returning `{}` by default, so maybe it's OK to release this as a minor semver update.
cc @redbmk
> Make initial option in map/reduce optional

- README.md
- index.js
- test/test.js
Removes the `initial` option completely, because we can do without it. See discussion in #114 for context. This is a breaking change, so will need a semver major bump. cc @redbmk
> Remove redundant initial option

- README.md
- index.js
- test/test.js
#114 introduced a bug in cluster aggregation where a shared reference to the same properties object from multiple clusters could lead to buggy behavior. This PR fixes the issue and adds additional safeguards for `map` against it.
> Fix a regression with cluster aggregation

- index.js
Closes #130. With this change, when `reduce` is set, `map` will only be called once per original point, rather per unclustered point per zoom. This improves performance of `map`/`reduce` slightly, but not significantly since `map` isn't a bottleneck in JS (although it might be with more complex `map` functions). cc @zmiao
> Avoid redundant map calls on reduce

- README.md
- index.js
- test/fixtures/places-z0-0-0-min5.json
- test/test.js
Adds an option to set the minimum points required to form a cluster (`2` by default).
> Introduce minPoints option

- index.js
- test/test.js
Fixes https://github.com/mapbox/mapbox-gl-js/issues/2898. Turned out to be a very tricky bug!
Basically, if you set a small cluster radius, same-location points would sometimes fail to cluster on higher zooms, because the point KD-tree index for querying uses `Float32Array` internally for smaller memory footprint, and that's generally enough precision for location data, except in case where we do small radius queries — in this case the query point was float64, while stored coordinates were float32, leading to the query returning zero results.
The fix is to round the internal stored coordinates to float32 outside the index as well, so that the values are consistent. `Math.fround` is the fast way to do that, but I'm still including a fallback for IE11 so that non-GL-JS consumers could …
> Fix small-radius clusters not always forming on higher zooms

- index.js
- test/test.js
Addresses https://github.com/mapbox/mapbox-gl-js/issues/10422 by recovering the original coordinate precision when returning unclustered point features in tiles instead of using the float32-rounded values used for indexing.
> Fix unclustered points snapping to a f32 grid

- index.js
- test/test.js
resolves #148 (I suspect followup comments after the original fix ran into this)
`zoom` is internally used to index into `trees`. some leaflet functions (e.g. `.flyTo()`) interpolate zoom values in which case calling methods like `.getClusters()` during interpolation causes a crash.
> fix: prevent crash when float  is passed as `zoom` value

- bench.js
- index.js
Instead of storing internal point and cluster data as arrays of objects, store everything in flat numeric arrays (except for map/reduced cluster properties). 
- Improves clustering performance by ~14-17%.
- Reduces memory overhead by 40–60%.
> Massively improve performance by using flat arrays internally
